/**
 * Vendor the two web fonts into `public/fonts/`.
 *
 * The stimulus typeface is an experimental control. Loading it from a CDN meant that a tablet in
 * aeroplane mode — which is how every session is run — rendered the reading passage in whatever
 * the device's default sans-serif happens to be, silently, differently on iPadOS and Android, and
 * with nothing in the export recording that it had happened. Letter shapes, stroke weight and
 * x-height all bear on reading speed and on how a colour is perceived against its background, so
 * that is a change to the independent variable, not a cosmetic one.
 *
 * Only the `latin` and `latin-ext` subsets are kept: the corpus, the questionnaires and the UI are
 * English, and the other subsets would multiply the payload for glyphs that are never drawn.
 *
 * Idempotent. Run `npm run vendor:fonts` to refresh; the outputs are committed so a clean checkout
 * builds without network access.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'fonts');
const CSS_URL = 'https://fonts.googleapis.com/css2?family=DM+Mono:wght@300;400;500&family=Roboto:wght@300;400;500&display=swap';
// A modern desktop UA is what makes Google Fonts serve woff2 rather than the legacy formats.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const KEEP = new Set(['latin', 'latin-ext']);

const fetchText = async (url) => {
  const r = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(`${r.status} ${r.statusText} for ${url}`);
  return r.text();
};

const css = await fetchText(CSS_URL);
await mkdir(OUT, { recursive: true });

// Google's CSS emits one commented subset name per @font-face, in order.
const blocks = css.split('/* ').slice(1);
const out = [];
let kept = 0;

for (const raw of blocks) {
  const subset = raw.slice(0, raw.indexOf(' */')).trim();
  if (!KEEP.has(subset)) continue;
  const body = raw.slice(raw.indexOf('*/') + 2);
  const family = /font-family:\s*'([^']+)'/.exec(body)?.[1];
  const weight = /font-weight:\s*(\d+)/.exec(body)?.[1];
  const style = /font-style:\s*(\w+)/.exec(body)?.[1] ?? 'normal';
  const src = /url\((https:[^)]+)\)/.exec(body)?.[1];
  const range = /unicode-range:\s*([^;]+);/.exec(body)?.[1];
  if (!family || !weight || !src) throw new Error(`could not parse a @font-face for subset ${subset}`);

  const file = `${family.replace(/\s+/g, '')}-${weight}-${style}-${subset}.woff2`;
  const bytes = new Uint8Array(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer());
  if (bytes.length < 1000) throw new Error(`${file} came back implausibly small (${bytes.length} bytes)`);
  await writeFile(resolve(OUT, file), bytes);
  kept++;

  out.push([
    `/* ${subset} */`,
    '@font-face {',
    `  font-family: '${family}';`,
    `  font-style: ${style};`,
    `  font-weight: ${weight};`,
    // `block` rather than `swap`: a flash of the fallback face mid-reading would be a change of
    // stimulus during the measurement window. Better a brief blank than a typeface that shifts.
    '  font-display: block;',
    `  src: url('/fonts/${file}') format('woff2');`,
    ...(range ? [`  unicode-range: ${range};`] : []),
    '}',
  ].join('\n'));
}

if (!kept) throw new Error('no latin faces were found in the stylesheet');

await writeFile(resolve(OUT, 'fonts.css'), `/* Generated by scripts/vendor-fonts.mjs. Do not edit by hand. */\n\n${out.join('\n\n')}\n`);
console.log(`vendored ${kept} font files into public/fonts/`);
