/// <reference types="vite/client" />
/*
 * The `virtual:pwa-register` module is generated by vite-plugin-pwa at build time, so its types
 * come from the plugin rather than from anything on disk here. src/lib/swUpdate.ts is the only
 * consumer. The build-time globals are declared in src/lib/env.ts, which also supplies the safe
 * fallbacks used when they are undefined.
 */
/// <reference types="vite-plugin-pwa/client" />
